Add packages which used for snc or crc
Recently we are seeing multiple failure on the CI because of following
error. Better to install all the packages before hand so no need to run
`yum install` or minimize the use of installing packages.

```
Red Hat Enterprise Linux 8 for x86_64 - Supplem 232  B/s | 1.0 kB     00:04
Errors during downloading metadata for repository 'rhui-rhel-8-for-x86_64-supplementary-rhui-rpms':
  - Status code: 404 for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/supplementary/os/repodata/7ddfb35cceeed63522dbf53f062dfd7526907c89f3dfa1146ab814aee77811fb-filelists.xml.gz (IP: 35.190.247.1)
  - Status code: 404 for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/supplementary/os/repodata/ecaf2b75f8c25ce599b6b6c3bd08f2e569e79b822e14a69a5f5b70dac3bb5e53-primary.xml.gz (IP: 35.190.247.1)
  - Status code: 404 for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/supplementary/os/repodata/2d994e18464a3c4ac93b6756961ac59ff947fbc2416ea477a653caa223da120b-updateinfo.xml.gz (IP: 35.190.247.1)
Error: Failed to download metadata for repo 'rhui-rhel-8-for-x86_64-supplementary-rhui-rpms': Yum repo downloading error: Downloading error(s): repodata/7ddfb35cceeed63522dbf53f062dfd7526907c89f3dfa1146ab814aee77811fb-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/ecaf2b75f8c25ce599b6b6c3bd08f2e569e79b822e14a69a5f5b70dac3bb5e53-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/2d994e18464a3c4ac93b6756961ac59ff947fbc2416ea477a653caa223da120b-updateinfo.xml.gz - Cannot download, all mirrors were already tried without success; repodata/f5ccc0ba10a5cd01ec4edac6b200cd48e8c0ab2262e05e7b6e0c7347a06e9b14-comps.xml - Cannot download, all mirrors were already tried without success
```

Packages which are added
make - To build the crc binary
tmux - To debug on running vm
unzip - To unpack the bundle zip file
podman - To test image feature e2e
rsync - [snc] Required for `oc rsync`
libguestfs-tools-c - [snc] Need for virt-filesystems
zstd - [snc] zstd compress tool
httpd-tools - [snc] For htpasswd provider for openshift
patch - [snc] patch command to apply web patch